repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^src/warden/gen/
      - id: trailing-whitespace
        exclude: ^src/warden/gen/
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/bufbuild/buf
    rev: v1.47.2
    hooks:
      - id: buf-lint
        args: [proto]
